server:
    port: 8000

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wishcart
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 2504
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL57Dialect
